/*
 * Connect4 compiled policy header.
 * Placeholder with synthetic data — a real C4 policy would be
 * generated by the tile-compiler trained on Connect4 games.
 */
#ifndef C4_POLICY_H
#define C4_POLICY_H
/* Include compiled_policy.h BEFORE this header. */

/* 20 representative Connect4 states (7-wide, 6-high = 42 chars) */
#define C4_POLICY_COUNT 20

static const PolicyEntry c4_entries[C4_POLICY_COUNT] = {
    {"a1b2c3d4e5f6a7b8", 3, 0.85f},  /* Center opening */
    {"0f1e2d3c4b5a6f7e", 3, 0.80f},
    {"1a2b3c4d5e6f7a1b2", 2, 0.78f},
    {"2c3d4e5f6a7b1c2d3", 4, 0.82f},
    {"3e4f5a6b7c1d2e3f4", 3, 0.90f},
    {"4a5b6c7d1e2f3a4b5", 3, 0.77f},
    {"5c6d7e1f2a3b4c5d6", 2, 0.75f},
    {"6e7f1a2b3c4d5e6f7a", 4, 0.79f},
    {"7b1c2d3e4f5a6b7c1d", 3, 0.83f},
    {"8e2f3a4b5c6d7e1f2a3", 3, 0.81f},
    {"9c4d5e6f7a1b2c3d4e5", 2, 0.74f},
    {"0a1b2c3d4e5f6a7b8c9", 4, 0.76f},
    {"1d2e3f4a5b6c7d1e2f3", 3, 0.88f},
    {"2a3b4c5d6e7f1a2b3c4", 3, 0.73f},
    {"3f4a5b6c7d1e2f3a4b5", 2, 0.71f},
    {"4b5c6d7e1f2a3b4c5d6", 4, 0.84f},
    {"5d6e7f1a2b3c4d5e6f7", 3, 0.86f},
    {"6a7b1c2d3e4f5a6b7c1", 3, 0.72f},
    {"7c1d2e3f4a5b6c7d1e2", 2, 0.70f},
    {"8e2f3a4b5c6d7e1f2a3b", 4, 0.87f},
};

static const CompiledPolicy c4_policy = {
    .entries = c4_entries,
    .count = C4_POLICY_COUNT,
    .temperature = 0.5f,
};

#endif /* C4_POLICY_H */
